# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:

        # Paramètrage de l'affichage des image sur les pages erreurs
        reduc:
            quality: 100
            filters:
                scale:
                    dim: [50, 50]