framework:
    default_locale: fr
    translator:
        # Mettre la/les langue(s) principale(s) du site pour générer seulement les fichier dans cette/ces langue(s)
        enabled_locales: [ 'fr' ]
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
