twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: '%site_name%'
        coefAM: '%coefAM%'
        coefMut: '%coefMut%'
        coefPrix: '%coefPrix%'
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true

