vich_uploader:
    db_driver: orm

    mappings:
        photo_equipement:
            uri_prefix: '%photo_equipement%'
            upload_destination: '%kernel.project_dir%/public%photo_equipement%'
            delete_on_update: false
            delete_on_remove: false
        photo_practitioner:
            uri_prefix: '%photo_practitioner%'
            upload_destination: '%kernel.project_dir%/public%photo_practitioner%'
            delete_on_update: false
            delete_on_remove: false